### ISSUE TITLE
Grid Selectors

### ISSUE THREAD

**Issue by megazear7** [megazear7/hackmastertrack#106]
Race, Class, Alignment, and Character List should all be a more visually appealing selection. Here is an example of something that I like:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Hackmastertrack Grid Example</title>
    <meta charset="utf-8">

    <style>
        .people .person {
            position: relative;
            display: inline-block;
            padding: 20px;
            margin: 10px;
            cursor: pointer;
            text-align: center;
            box-shadow: 1px 1px 1px 1px #ccc;
            bottom: 0px;
            right: 0px;
            transition: box-shadow .3s, bottom .3s, right .3s;
        }

        .people .person.important {
            background: lightblue;
        }

        .people .person.unimportant {
            background: aliceblue;
        }

        .people .person:hover {
            box-shadow: 3px 3px 10px 3px #ccc;
            bottom: 10px;
            right: 5px;
        }
    </style>
</head>
<body>
    <div class="people">
        <div class="person important">
            <h3>Bob</h3>
            <hr/>
            <p>Bob is a pretty cool guy.</p>
        </div>

        <div class="person unimportant">
            <h3>Steve</h3>
            <hr/>
            <p>Steve is kind of a jerk.</p>
        </div>

        <div class="person unimportant">
            <h3>Joseph</h3>
            <hr/>
            <p>badfasdf adsf asd</p>
        </div>
    </div>
</body>
</html>
```

**Comment by megazear7** [comment]
Will making the character creation form for selecting race/class/alignment and selecting a character to view be confusing? I think it will be okay, you can make them different and contain different content based on the situation to convey the difference.

How will this work with bootstrap? Can each ".person" in the above example be a ".col-md-#" in bootstrap?

**Comment by megazear7** [comment]
An example is on the character listing page.

What do you think about adding this style of tiles to purchase pages? So instead of having a table with rows of items, skills, talents, proficiencies, there is a grid of options?

**Comment by BuckRogers1965** [comment]
This might work if we can keep the departments. Maybe even just go into a page with just armor or just melee weapons. We might even be able to put a little picture in each of the tiles that represents that item.

**Comment by megazear7** [comment]
Wouldn't the purchase pages be the same regardless of level? Except some of the things would have the green checkmark next to it if that character has it.

**Comment by BuckRogers1965** [comment]
I think I am confused, I was thinking you were talking about the list of skills talents and proficiencies on the character page. *L*

**Comment by megazear7** [comment]
Ah yeah I meant the listing pages where you can purchase them. Mikayla suggested having big obvious categories in the item list sub nav.

**Comment by megazear7** [comment]
This has been implemented multiple places. More specific issues can be created to utilize the tile design in other places.
