### ISSUE TITLE
Item, round 4 fixes

### ISSUE THREAD

**Issue by BuckRogers1965** [megazear7/hackmastertrack#17]
Add the following categories and columns to reflect the book:  

Religious?

Illumination
     distance
     illum_type
     right now this info is only in GM guide, maybe steal info from earlier hackmaster book?

Expedition Gear

Tools

Scribe Materials

Musical Instruments

Spice and Herbs

Beverages / Alcohol   (move a few liquid items from food to here?)
    Gallons?
    Special effects?

Livestock

Tack and Harness

---

And then enter the data for all these types.

**Comment by megazear7** [comment]
Are all the items in now? It looks like they are.

**Comment by BuckRogers1965** [comment]
We can close this.  I can just add spell component stuff as I go.
