### ISSUE TITLE
Spells

### ISSUE THREAD

**Issue by BuckRogers1965** [megazear7/hackmastertrack#18]
We did a first cut of this, but didn't try to add any spells yet. 

We need to add more columns:

clerical or magical.  
level of the spell.
list of damage types:  charm, poison, acid, cold, fire, impact, energy.  this would help when calculating saving throws.
elemental type for later expansions.  earth, air, fire, water, energy.

Range of the spell.
Area of effect type:  none, square, cone, sphere, multiple 
area damage: similar to weapon damage
damage to opponent: how much does primary damage do, like weapon damage dice

How much to boost primary damage.
By how much damage.

How much to boost area damage.
by how much damage.

How much to boost range
By how much range each boost

How much to boost area of effect
by how much area?

For cleric, don't show spell points or anything related to boosting by spell points.

I need to read a bunch of the clerical spells to see how clerical magic works.

**Comment by megazear7** [comment]
@BuckRogers1965  can we close this now? we can probably make more specific issues for specific spell related features.
