### ISSUE TITLE
Skills list doesn't auto hide the accordion.

### ISSUE THREAD

**Issue by megazear7** [megazear7/hackmastertrack#55]
<img width="1181" alt="hacktrack" src="https://cloud.githubusercontent.com/assets/4239926/16663728/32ae9652-444b-11e6-9b16-37fd40802c7f.png">

**Comment by BuckRogers1965** [comment]
This looks fixed to me by that change you made to put it at the end of the line.

**Comment by megazear7** [comment]
yep
