### ISSUE TITLE
Store loses track of who is shopping.

### ISSUE THREAD

**Issue by BuckRogers1965** [megazear7/hackmastertrack#58]
I created a new character, went to store, bought something, then bought something else, and suddenly someone else in my character list was shopping.  In a similar note I have to choose who gets each skill and talent.

**Comment by megazear7** [comment]
This isn't so much of a bug as a poor feature. Basically those "+" links just take you to the items/proficiencies/talents/skills lists and then let's you pick from there and choose a character. Did this cause major confusion or was it just an inconvenience?

**Comment by megazear7** [comment]
Closing: this will be outdated when the changes in #62 are implemented.
