### ISSUE TITLE
The path class_spellbooks doesnt exist

### ISSUE THREAD

**Issue by megazear7** [megazear7/hackmastertrack#81]
there is a link to this in the admin section.

**Comment by BuckRogers1965** [comment]
I wonder if this just got partially put in from work I did a while ago, because I could have sworn that I remember being able to add magic user spells to my spell book and list them in the pdf.  I wonder if that is why I can't bring up that magic user I made before.

**Comment by BuckRogers1965** [comment]
I found the table with a different name in the development version.
