### ISSUE TITLE
Penalties for nonproficient weapons.

### ISSUE THREAD

**Issue by BuckRogers1965** [megazear7/hackmastertrack#83]
If I equip a weapon that I am not proficient in, then I should get an attack and damage penalty for using that weapon.  The damage penalty depends on what skill level the weapon is.  Maybe add a weapon skill  table and add a column to the weapon to select the weapon skill for the penalty and bp training cost? Did I do this already? *L*

From the hackmaster basic manual... was this changed in the regular manual?

Minima1 Skill Weapon (1 BP cost): These weapons can be
used by anyone without any formal training and very little
practice. These weapons are so easy to use that characters
receive a mere -1 to attack, defense, speed and damage when
using this weapon untrained. [club, sap, garrote]
Low Skill Weapon (2 BP cost}: Proper use of these weapons
is not inNitive but the proper techniques are relatively easy to
learn if instructed by a knowledgeable trainer. These weapons
are relatively easy to use; characters receive a penalty of -2 to
attack, defense, speed and damage when using these weapons
untrained (attack and speed only for ranged weapons). [battle
axe, dagger, flail ,javelin, knife, mace, morning star, short sword,
spear, scourge, staff, warhammer, two-handed warhammer,
crossbow]
Medium Skill Weapon (4 BP cost): These weapons require
a good deal more training to master. Proper use requires
lengthy practice and familiarization with the weapon in actual
sparring or extended practice to master the technique (in the
case of thrown weapons). As they are more difficult to master,
11characters receive a -4 to attack, defense, speed and damage if
using these untrained (attack and speed only for ranged
weapon s). [great axe, greatlbastard sword, halberd, long sword,
scimitar, short bow, sling, throwing axe, throwing knife, two-
handed sword]
High Skill Weapon (6 BP cost): These represent the pinna-
cle of finesse weapons that require years of practice to master.
Characters receive a -6 to attack and speed when using these
untrained. [long bow]

**Comment by megazear7** [comment]
@BuckRogers1965 Are you still seeing this? It looks to be applying correctly for me.

**Comment by megazear7** [comment]
As far as I can tell the proficiencies are being accounted for (negative applied if you dont have it).

Closing.
