### ISSUE TITLE
Skills text box entry not showing die size to roll.

### ISSUE THREAD

**Issue by BuckRogers1965** [megazear7/hackmastertrack#96]
The size of die to add to a skill depends on existing skill level.

Plus, I hit enter on a skill for Elfin and it gave me an 11 in that skil.... Did it roll the die for me and add it to bonuses? Or did it just take the non-entry as a zero?

**Comment by megazear7** [comment]
The initial purchase of a skill gives you the die roll plus your relevant
ability score. As for the placeholder text, yeah that would be very useful
that is important to have.
