### ISSUE TITLE
Automatic dice roll option

### ISSUE THREAD

**Issue by BuckRogers1965** [megazear7/hackmastertrack#97]
If I don't fill in values for a die roll box, roll the given dice for me when I hit next.  This matters on ability scores, starting hit points, starting gold, and skill increases.

**Comment by megazear7** [comment]
Rather than this, just require a die roll on those forms, and provide a button to do the roll for the user. This has already been done in character creation step 2.

**Comment by megazear7** [comment]
Updating the issue name to match what we want to do with the dice rolls.

Make the ".random" class more robust to have a data attribute where you can explain what dice sizes you need. Then use this class throughout the site for the die rolls.

**Comment by megazear7** [comment]
finished
